config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'posts#index'
  
  resources :users
  
  resources :posts do
    resources :reviews
  end
  
  resources :followings
  

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :favoriting_user, class_name: "User"
  belongs_to :favorited_post, class_name: "Post"
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :leader, class_name: "User"
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :reviews, foreign_key: "reviewed_post_id"
  
  has_many :favorites, foreign_key: "favorited_post_id"
  has_many :favoriting_users, through: :favorites, source: :favoriting_user
  
  has_many :taggings, foreign_key: "tagged_post_id"
  has_many :tags, through: :taggings, source: :tag
  
  has_many :ingredients
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  
  has_attached_file :image, styles: { small:"200x200", large:"500x500" }
  
  validates :title, presence: true
  validates :directions, presence: true
  validates :author_id, presence: true
  
  
  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :review_author, class_name: "User"
  belongs_to :reviewed_post
  
  validates :content, presence: true
  validates :rating, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, foreign_key: "tag_id"
  has_many :tagged_posts, through: :taggings, source: :tagged_post
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :tagged_post, class_name: "Post"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts, foreign_key: "author_id"
  has_many :reviews, foreign_key: "review_author_id"
  
  has_many :followings, foreign_key: "follower_id", dependent: :destroy
  has_many :leadings, class_name: "Following", foreign_key:"leader_id", dependent: :destroy
  
  has_many :followers, through: :leadings, source: :follower
  has_many :leaders, through: :followings, source: :leader
  
  has_many :favorites, foreign_key: "favoriting_user_id"
  has_many :favorited_posts, through: :favorites, source: :favorited_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @following = Following.new
    @following.leader_id = params[:user_id]
    @following.follower_id = current_user.id
    @following.save
    redirect_to User.find(params[:user_id])
  end
  
  def destroy
    @user = User.find(params[:user_id])
    @user.followings.find_by(follower_id: current_user.id).destroy
    
    redirect_to user_path(User.find(params[:user_id]))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @review = Review.new
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :image, :directions,
        ingredients_attributes: [:id,  :content, :_destroy] )
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  
  def create
    @post = Post.find(params[:post_id])
    @review = @post.reviews.build(review_params)
    @review.review_author_id = current_user.id
    @review.save
    redirect_to @post
  end
  
  def edit
    @post = Post.find(params[:post_id])
    @review = Review.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:post_id])
    @review = Review.find(params[:id])
    authorize_user(@review)
    @review.update_attributes(review_params)
    @review.save
    redirect_to @post
  end
  
  def destroy
    @review = Review.find(params[:id])
    @post = Post.find(params[:post_id])
    authorize_user(@review)
    @review.destroy
    redirect_to @post
  end
  
  private
  
    def review_params
      params.require(:review).permit(:rating, :content)
    end
    
    def authorize_user(review)
      unless review.review_author == current_user
        flash[:notice] = "You must be the author of this review to proceed."
        redirect_to review.reviewed_post
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @following = Following.new 
    @f = Following.where("leader_id = ? AND follower_id = ?", @user.id, current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BonApp</title>
  <link href='https://fonts.googleapis.com/css?family=Vollkorn|Montserrat:700,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Log out" %><li>
      <% else %>
        <li> <%= link_to "Log in", new_user_session_path %> </li>
        <li> / </li>
        <li><%= link_to "Sign up", new_user_registration_path%></li>
      <% end %>
    </ul>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/posts/_ingredient.html.erb
<%= f.text_field :content %> 
<%= link_to_remove_association "Remove ingredient", f %>

app/views/posts/_ingredient_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :content %> 
  <%= link_to_remove_association "Remove ingredient", f %>
</div>

app/views/posts/_review_form.html.erb
<%= form_for review, url: post_reviews_path(post) do |f| %>
    <% 5.times do |n| %>
      <%= f.label n+1 %>
      <%= f.radio_button(:rating, n+1) %><br>
    <% end %>
    <%= f.text_area :content %>
    <%= f.submit "POST" %>
<% end %>

app/views/posts/edit.html.erb
<%= render partial:'review form', locals: { review: @review, post: @post } %>

app/views/posts/index.html.erb
<div class="container">
  all the posts
  
  <%= link_to "new post", new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="post-form-container">
  <div class="form-content box">
    <div class="form-title box">
      <h2> NEW POST </h2>
    </div>
   
    
    <%= form_for @post, html: { multipart: true } do |f| %>
      <% if @post.errors.any? %>
      <div id="error_explanation">
        <h3>Sorry! There was a problem saving your post!</h3>
        <ul>
          <% @post.errors.messages.each do |attr, errors| %>
            <% errors.each do |error| %>
              <li> <%= attr %> <%= error %> </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <% end %>
      
      <%= f.text_field :title, placeholder: "Title" %><br>
      <%= f.file_field :image %><br>
      <div class="ingredients">
        <%= f.fields_for :ingredients do |ingredient| %>
          <%= render partial: 'ingredient_fields', f: ingredient %>
        <% end %>
        <%= link_to_add_association "Add ingredient", f, :ingredients %><br>
        
      </div>
      <%= f.label "Directions", class:"space" %><br>
      <%= f.text_area :directions %><br>
      <%= f.submit "POST" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h2> <%= @post.title %> </h2>
  <%= image_tag @post.image.url(:large) %>
  <ol>
    <% @post.ingredients.each do |i| %>
      <li><%= i.content %></li>
    <% end %>
  </ol>
  <p><%= @post.directions %></p>
  
  <%= render partial:'review_form', locals: { review: @review, post: @post } %>
  
  <% @post.reviews.each do |review| %>
    <p> Rating: <%=review.rating %> </p>
    <% if current_user == review.review_author %>
      <p> 
        <%= link_to "delete review", post_review_path(@post, review), method: :delete %> 
        | <%= link_to "edit review", edit_post_review_path(@post, review) %>
      </p>
    <% end %>
    <p> <%= review.review_author.email %>: <%= review.content %></p>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<%= form_for @review, url: post_review_path(@post, @review) do |f| %>
    <% 5.times do |n| %>
      <%= f.label n+1 %>
      <%= f.radio_button(:rating, n+1) %><br>
    <% end %>
    <%= f.text_area :content %>
    <%= f.submit "POST" %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.email%></h1>
<%= pluralize( @user.followers.count, "follower") %>

<% if current_user.followers.include? @user %>
  <%= button_to "Unfollow", {controller:"followings", action:"destroy", user_id: @user.id }, method: :delete %>
<% else %>
  <%= button_to "Follow", { controller: "followings", action:"create", user_id: @user.id }%>
<% end %>